### ISSUE TITLE
Pubchem name question

### ISSUE THREAD

**Issue by bgyori** [biopragmatics/biolookup#9]
When looking up https://biolookup.io/api/lookup/pubchem.compound:4896, I get
```
{
  "identifier": "4896",
  "name": "Orapred",
  "prefix": "pubchem.compound",
  "providers": {
    "biolookup": "http://biolookup.io/pubchem.compound:4896",
    "bioregistry": "https://bioregistry.io/pubchem.compound:4896",
    "default": "https://pubchem.ncbi.nlm.nih.gov/compound/4896",
    "miriam": "https://identifiers.org/pubchem.compound:4896",
    "n2t": "https://n2t.net/pubchem.compound:4896"
  },
  "query": "pubchem.compound:4896",
  "success": true
}
```

but at https://pubchem.ncbi.nlm.nih.gov/compound/4896 I actually see a different (much longer) name and in fact Orapred doesn't appear anywhere on the page. What could be going on here?

**Comment by cthoyt** [comment]
Next week I will look back into deploying the new version of this service that has synonyms as well, maybe that will give us some insight. It’s also possible the title has been updated since the last deploy

**Comment by cthoyt** [comment]
http://biolookup.io/api/lookup/pubchem.compound:4896 is now better reflecting what's on the new page. There's no mention of Orapred there, but it can be found in synonyms of this entry in the `pubchem.substance` database https://pubchem.ncbi.nlm.nih.gov/substance/134975392.
